version: '3.8'
services:
  db:
    image: timescale/timescaledb:latest-pg16 
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stock_market_db
    volumes:
      - stock_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
    
volumes:
  stock_data: