name: AI Stock Pipeline CI/CD and Daily MLOps Run

on:
  # 1. Trigger on Push (for CI/CD checks)
  push:
    branches:
      - automation
      
  # 2. Trigger on Schedule (The MLOps Scheduler)
  schedule:
    # Runs the pipeline daily at 00:30 UTC (approx. 6:00 AM IST)
    - cron: '30 0 * * *' 

jobs:
  # Job 1: Build, Lint, and Push the Docker Image (Your CI/CD)
  build_and_push_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push MLOps image
        uses: docker/build-and-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/master-trader-airflow:latest
          file: ./Dockerfile

  # Job 2: Run the Live MLOps Pipeline (The Airflow Replacement)
  run_daily_pipeline:
    # This job runs *after* the build, or on its own schedule
    runs-on: ubuntu-latest
    needs: build_and_push_docker # Only runs if the build is successful
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          
      - name: Install All Python Dependencies
        run: pip install -r requirements.txt
        
      - name: Run Full MLOps Pipeline
        # Inject the cloud database URL from GitHub Secrets
        env:
          DATABASE_URL: ${{ secrets.RENDER_DB_URL }} 
        run: |
          echo "Starting Daily Pipeline Run..."
          
          # Task 1: Ingest Data (Watermarked)
          python scripts/ingestion/ingest_data.py
          
          # Task 2: Feature Engineering (WFO Features)
          python scripts/features/transform_features.py
          
          # Task 3: AI Training (WFO Model)
          python scripts/ai/train_ai_model.py
          
          echo "MLOps Pipeline run completed successfully."