# .streamlit/secrets.toml

# Full PostgreSQL connection URL from Render (including postgresql+psycopg2://driver)
DATABASE_URL = "postgresql+psycopg2://ai_stock_trader_user:WcPpqu1IDRnqv95NoV1dUsMp17RCbTMR@dpg-d3rijvur433s73e6adeg-a.oregon-postgres.render.com/ai_stock_trader?sslmode=require"